Profile/urls.py
from django.contrib import admin
from django.urls import path

from .views import ProfileDetailView,FollowView,UpdateProfileView


app_name='profile'
urlpatterns = [
    path("<str:username>/",ProfileDetailView.as_view(),name="detail"),
    path("<str:username>/follow/",FollowView.as_view(),name="follow"),
    path("<int:pk>/update/",UpdateProfileView.as_view(),name='update')

]

Project1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from feed import urls as feed_urls
from Profile import urls as profile_urls
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include(feed_urls,namespace='feed')),
    path('', include('allauth.urls')),
    path("profile/",include(profile_urls,namespace='profile'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

feed/urls.py
from django.contrib import admin
from django.urls import path
from .views import HomePage,PostDetailView,PostCreateView

app_name='feed'
urlpatterns = [
    path("",HomePage.as_view(),name='index'),
    path("<int:pk>",PostDetailView.as_view(),name="detail"),
    path("new/",PostCreateView.as_view(),name='new-post'),
    
]

Profile/models.py
from django.db import models
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField
from django.dispatch import receiver
from django.db.models.signals import post_save
class Profile(models.Model):
    user=models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile'
    )
    first_name=models.CharField( max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    username=models.CharField(max_length=150, blank=True)
    password=models.CharField(max_length=150, blank=True)
    image=ImageField(upload_to='profiles')
    def __str__(self):
        return self.user.username 
    
    @receiver(post_save,sender=User)
    def create_user_profile(sender,instance,created,**kwargs):
        if created:
            Profile.objects.create(user=instance)

    

Profile/views.py
from django.views.generic import DetailView,UpdateView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseBadRequest,JsonResponse
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth import update_session_auth_hash
from feed.models import Post
from follower.models import Follower

class ProfileDetailView(DetailView):
    http_method_names=["get"]
    model = User
    context_object_name="user"
    template_name="profile/detail.html"
    slug_field="username"
    slug_url_kwarg = 'username'
    
    def dispatch(self,request,*args,**kwargs):
        self.request=request
        return super().dispatch(request,*args,**kwargs)
    
    
        
    
    def get_context_data(self,**kwargs) :
        user=self.get_object()
        context = super().get_context_data(**kwargs)
        context["total_posts"] = Post.objects.filter(author=user).count()
        context["total_followers"]=Follower.objects.filter(following=user).count()
        if self.request.user.is_authenticated:
            context["you_follow"]=Follower.objects.filter(followed_by=self.request.user,following=user).exists()
            return context
"""button click->action and user is send from js->in views---checking that sended user is exist,checking the s
sended data has action and user,checking the action if it is "follow"  check the follwwing object is already there unless create it.
--if action is "unfollow" ,checking that following object is there..if it is there delete that following user that is the unfollow.
--then send a jsonresponse from views.py into js saying it is sucess and wording i the button.
"""    
class FollowView(LoginRequiredMixin,View):
    http_method_names=["post"]
    def post(self,request,*args,**kwargs):
        data=request.POST.dict()
        if "action" not in data or "username" not in data:
            return HttpResponseBadRequest("Missing data")
        try:   
            other_user=User.objects.get(username=data["username"])
        except User.DeosNotExist:
            return HttpResponseBadRequest("Missing user")
        if data["action"]=="follow":
            follower,created=Follower.objects.get_or_create(
                followed_by=request.user,
                following=other_user
            )
        else:
            try:
                follower=Follower.objects.get(
                    followed_by=request.user,
                    following=other_user
                )
            except Follower.DoesNotExist:
                follower=None
                
            if follower:
                follower.delete()
        print("before wording-",data["action"])
        return JsonResponse({
            "success":True,
           "wording":"Unfollow" if data["action"] =="follow" else "Follow"
            #first action is "follow" then we followed and text should change to "unfollow" viceversa
            
        }
        )
            

class UpdateProfileView(UpdateView):
    model=Profile
    template_name="profile/update_profile.html"
    fields=['first_name', 'last_name','username','password', 'image']
    success_url='/'
    
    def get_object(self,query_set=None):
        return self.request.user.profile
    
    def form_valid(self, form):
        username=form.cleaned_data['username']
        password=form.cleaned_data['password']
        
        
        # Update user information
        self.request.user.username=username
        if password: 
            self.request.user.set_password(password)
            
            self.request.user.save()
        # # Update session if password changed
            update_session_auth_hash(self.request, self.request.user)
        else:
            self.request.user.save()
            
        return super().form_valid(form)
    

Profile/templates/profile/detail.html
{%extends 'base.html'%}
{% load thumbnail %}
{%block title%}{{user.username}}
{%endblock%}
{%block body %}
<!-- component -->
<div class="rounded-3xl overflow-hidden shadow-xl max-w-xs my-3 ">
    <img src="https://i.imgur.com/dYcYQ7E.png" class="w-full" />
  <div class="flex justify-center -mt-8">
    {% thumbnail user.profile.image "100x100" crop="center" as im %}
        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"class="mx-4  object-cover rounded-full hidden sm:block" alt="avatar">
    {% endthumbnail %}
      {% comment %} <img src="https://i.imgur.com/8Km9tLL.jpg" class="rounded-full border-solid border-white border-2 -mt-3">		 {% endcomment %}
  </div>
  <div class="text-center px-3 pb-6 pt-2">
      <h3 class="text-black text-sm bold font-sans">{{user }}</h3>
  </div>

    {%if request.user.is_authenticated%}
        {%if request.user != user %}
            <div class="my-3">
                <button
                class=" m-auto flex select-none items-center gap-3 rounded-lg bg-gradient-to-tr from-pink-600 to-pink-400 py-3 px-6 text-center align-middle font-sans text-xs font-bold uppercase text-white shadow-md shadow-pink-500/20 transition-all hover:shadow-lg hover:shadow-pink-500/40 active:opacity-[0.85] disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none js-follow"
                type="button"
                data-url="{% url 'profile:follow' user.username %}"
                data-username="{{user.username}}"
                data-action="{% if you_follow  %}un{%endif%}follow"
                data-ripple-light="true"
                    >
                    <span class="js-follow-text">
                        {% if you_follow %}
                            Unfollow
                        {%else%}
                            Follow
                        {%endif%}
                    </span>
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="2"
                    stroke="currentColor"
                    aria-hidden="true"
                    class="h-5 w-5"
                >
                <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                    
                </svg>
                
                </button>
            </div>
        {%endif%}
    {%else%}
        <div class="mt-3 text-sm">Login to follow the user</div>
    {%endif%}
    
    <div class="flex justify-center pb-3 text-black">
        
    <div class="text-center mr-3 border-r pr-3">
      <h2>{{total_posts}}</h2>
      <span>Posts</span>
    </div>
    <div class="text-center">
      <h2>{{total_followers}}</h2>
      <span>Followers</span>
    </div>
    </div>
</div>
{%endblock%}

Profile/templates/profile/update_profile.html
{% extends 'base.html' %}
{% block title %}Update Profile{% endblock %}
{% block body %}
<div class="flex  items-center justify-center  dark:bg-gray-950 ">
    <form action="" method="post" enctype="multipart/form-data" class="max-w-sm rounded-3xl bg-gradient-to-b from-sky-300 to-purple-500 p-px dark:from-gray-800 dark:to-transparent ">
        <div class="rounded-[calc(1.5rem-1px)] bg-white px-10 p-12 dark:bg-gray-900">
          <div>
            <h1 class="text-xl font-semibold text-gray-800 dark:text-white">Update Your Profile</h1>
          </div>
  
          <div class="mt-8 space-y-8">
            <div class="grid grid-cols-1 gap-6"">
                {% csrf_token %}
                {% comment %} The for attribute in a <label> element specifies which form element the label is associated with.
                    It takes the id attribute value of the corresponding form element as its value. 
                    The id attribute uniquely identifies an element in an HTML document.
                    It must be unique within the entire document.
                    The id attribute value is used in the for attribute of the corresponding <label> element.{% endcomment %}
                <div class="flex items-center">
                    <label for="id_first_name" class="block text-sm font-medium text-gray-700 dark:text-white mr-4" >First Name</label>
                    <input id="id_first_name" name="first_name" type="text" class="form-control w-full bg-transparent text-gray-600 dark:text-white dark:border-gray-700 rounded-md border border-gray-300 px-3 py-2 text-sm placeholder-gray-600 invalid:border-red-500 dark:placeholder-gray-300" placeholder="Your First Name" required />
                  </div>
                  
                  <div class="flex items-center">
                    <label for="id_last_name" class="block text-sm font-medium text-gray-700 dark:text-white mr-4">Last Name</label>
                    <input id="id_last_name" name="last_name" type="text" class="form-control w-full bg-transparent text-gray-600 dark:text-white dark:border-gray-700 rounded-md border border-gray-300 px-3 py-2 text-sm placeholder-gray-600 invalid:border-red-500 dark:placeholder-gray-300" placeholder="Your Last Name" required />
                  </div>

                  <div class="flex items-center">
                    <label for="id_username" class="block text-sm font-medium text-gray-700 dark:text-white mr-4">Username</label>
                    <input id="id_username" name="username" type="text" class="form-control w-full bg-transparent text-gray-600 dark:text-white dark:border-gray-700 rounded-md border border-gray-300 px-3 py-2 text-sm placeholder-gray-600 invalid:border-red-500 dark:placeholder-gray-300" placeholder="Your Username" required />
                  </div>
        
                  <div class="flex items-center">
                    <label for="id_password" class="block text-sm font-medium text-gray-700 dark:text-white mr-4">Password</label>
                    <input id="id_password" name="password" type="password" class="form-control w-full bg-transparent text-gray-600 dark:text-white dark:border-gray-700 rounded-md border border-gray-300 px-3 py-2 text-sm placeholder-gray-600 invalid:border-red-500 dark:placeholder-gray-300" placeholder="Your Password" required />
                  </div>
        
                  <div class="flex items-center">
                    <label for="id_image" class="block text-sm font-medium text-gray-700 dark:text-white mr-4">Profile Image</label>
                    <input id="id_image" name="image" type="file" class="form-control w-full bg-transparent text-gray-600 dark:text-white dark:border-gray-700 rounded-md border border-gray-300 px-3 py-2 text-sm placeholder-gray-600 invalid:border-red-500 dark:placeholder-gray-300" required />
                  </div>
            </div>
  
            <button class="h-9 px-3 w-full bg-blue-600 hover:bg-blue-700 active:bg-blue-800 focus:bg-blue-700 transition duration-500 rounded-md text-white" type="submit">
                Update
            </button>
          </div>
        </div>
    </form>
</div>    
{% endblock %}