Project1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from feed import urls as feed_urls
from Profile import urls as profile_urls
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include(feed_urls,namespace='feed')),
    path('', include('allauth.urls')),
    path("profile/",include(profile_urls,namespace='profile'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

feed/urls.py
from django.contrib import admin
from django.urls import path
from .views import HomePage,PostDetailView,PostCreateView

app_name='feed'
urlpatterns = [
    path("",HomePage.as_view(),name='index'),
    path("<int:pk>",PostDetailView.as_view(),name="detail"),
    path("new/",PostCreateView.as_view(),name='new-post'),
    
]

Project1/templates/includes/post.html
{% load thumbnail %}


<div class="max-w-4xl md:w-50 px-10 my-4 py-6 bg-white rounded-lg shadow-md" >
    <div class="flex justify-between items-center">
        <span class="font-light text-gray-600">{{post.date|date:"F j, Y, g:i :a"}}</span>
    </div>
    <div class="mt-2">
        <p class="mt-2 text-gray-600 ">{{post.text}}</p>
    </div>
    <div class="flex justify-between items-center mt-4">
        {% if show_detail_view %}
            <a class="text-blue-600 hover:underline" href="{% url 'feed:detail' pk=post.id %}">Read more</a>
        {%else%}
            <span></span>
        {%endif%}
        <div>
            <a class="flex items-center" href="{% url 'profile:detail' post.author.username %}">
                {% thumbnail post.author.profile.image "50x50" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block" alt="avatar">
                {% endthumbnail %}
                <h1 class="text-gray-700 font-bold">{{post.author}}</h1>
            </a>
        </div>
    </div>
</div>
{% comment %} 
<!-- component -->
<div class="max-w-4xl px-10 my-4 py-6 bg-white rounded-lg shadow-md" >
    <div class="flex justify-between items-center">
        <span class="font-light text-gray-600">mar 10, 2019</span>
        
    </div>
    <div class="mt-2">
        <p class="mt-2 text-gray-600">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque. Excepturi iste iusto eos enim reprehenderit nisi, accusamus delectus nihil quis facere in modi ratione libero!</p>
    </div>
    <div class="flex justify-between items-center mt-4">
        <a class="text-blue-600 hover:underline" href="#">Read more</a>
        <div>
            <a class="flex items-center" href="#">
                <img class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block" src="https://images.unsplash.com/photo-1502980426475-b83966705988?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=373&q=80" alt="avatar">
                <h1 class="text-gray-700 font-bold">Khatab wedaa</h1>
            </a>
        </div>
    </div>
</div>


<div class="max-w-4xl px-10 my-4 py-6 bg-white rounded-lg shadow-md" >
    <div class="flex justify-between items-center">
        <span class="font-light text-gray-600">{{post.date|date:"F j, Y, g:i :a"}}</span>
        
    </div>
    <div class="mt-2">
        <p class="mt-2 text-gray-600">helllooooooooooooooooooooooooo kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk kkkdddddddddddddddddddddddddddddddddddddddddddddd</p>
    </div>
    <div class="flex justify-between items-center mt-4">
        <a class="text-blue-600 hover:underline" href="#">Read more</a>
        <div>
            <a class="flex items-center" href="#">
                <img class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block" src="https://images.unsplash.com/photo-1502980426475-b83966705988?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=373&q=80" alt="avatar">
                <h1 class="text-gray-700 font-bold">Khatab wedaa</h1>
            </a>
        </div>
    </div>
</div> {% endcomment %}